Repository codestates-seb/seb42_main_008, pull requests merged in 2023-03, with the labels that each got.

#91 Feat/jgs/member
  server/build.gradle
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthorizationFilter.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/partypeople/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/partypeople/server/auth/userdetails/MemberDetailService.java
  server/src/main/java/partypeople/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/partypeople/server/auth/utils/ErrorResponder.java
  server/src/main/java/partypeople/server/config/BeanConfig.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/dto/MemberDto.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/mapper/MemberMapper.java
  server/src/main/java/partypeople/server/member/repository/MemberRepository.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: 기능, [BE]조국선, 필수

#99 Feat/jgs/member
  server/src/main/java/partypeople/server/PartypeopleApplication.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
  server/src/main/java/partypeople/server/init/initDb.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/dto/FollowDto.java
  server/src/main/java/partypeople/server/member/dto/MemberDto.java
  server/src/main/java/partypeople/server/member/entity/Follow.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/mapper/MemberMapper.java
  server/src/main/java/partypeople/server/member/repository/FollowRepository.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
Labels: 기능, [BE]조국선, 필수

#100 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/controller/CompanionController.java
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/entity/Companion.java
  server/src/main/java/partypeople/server/companion/entity/CompanionTag.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/main/java/partypeople/server/companion/repository/CompanionRepository.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
  server/src/main/java/partypeople/server/init/initDb.java
  server/src/main/java/partypeople/server/nation/entity/Nation.java
  server/src/main/java/partypeople/server/nation/repository/NationRepository.java
  server/src/main/java/partypeople/server/nation/service/NationService.java
  server/src/main/java/partypeople/server/tag/entity/Tag.java
  server/src/main/java/partypeople/server/tag/repository/TagRepository.java
  server/src/main/java/partypeople/server/tag/service/TagService.java
Labels: 기능, [BE]홍수경, 필수

#111 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
Labels: 버그, [BE]홍수경

#116 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/controller/CompanionController.java
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/main/java/partypeople/server/companion/repository/CompanionTagRepository.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
Labels: [BE]홍수경, 필수

#123 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/controller/CompanionController.java
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/entity/Companion.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/main/java/partypeople/server/companion/repository/CompanionRepository.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
Labels: [BE]홍수경, 필수, 부가

#126 Feat/jgs/member
  server/src/main/java/partypeople/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthorizationFilter.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/partypeople/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/entity/Companion.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/main/java/partypeople/server/companion/repository/CompanionRepository.java
  server/src/main/java/partypeople/server/companion/repository/ParticipantRepository.java
  server/src/main/java/partypeople/server/companion/repository/SubscriberRepository.java
  server/src/main/java/partypeople/server/companion/service/ParticipantService.java
  server/src/main/java/partypeople/server/companion/service/SubscriberService.java
  server/src/main/java/partypeople/server/config/BeanConfig.java
  server/src/main/java/partypeople/server/exception/BusinessLogicException.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
  server/src/main/java/partypeople/server/init/initDb.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/repository/FollowRepository.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/review/repository/ReviewRepository.java
  server/src/main/resources/application.yml
Labels: [BE]조국선

#138 Feat/hsg/companion
  server/src/main/java/partypeople/server/PartypeopleApplication.java
  server/src/main/java/partypeople/server/companion/controller/CompanionController.java
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/dto/SubscriberParticipantDto.java
  server/src/main/java/partypeople/server/companion/repository/CompanionRepository.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
  server/src/main/java/partypeople/server/review/repository/ReviewRepository.java
  server/src/main/java/partypeople/server/review/service/ReviewService.java
Labels: [BE]홍수경, 부가

#142 Feat/jgs/member
  server/build.gradle
  server/src/main/java/partypeople/server/PartypeopleApplication.java
  server/src/main/java/partypeople/server/auth/AuthService.java
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/init/initDb.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/dto/MemberDto.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/mapper/MemberMapper.java
  server/src/main/java/partypeople/server/member/service/MailService.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/review/service/ReviewService.java
  server/src/test/java/partypeople/server/config/SecurityConfigurationTest.java
  server/src/test/java/partypeople/server/member/controller/MemberControllerRestDocsTest.java
  server/src/test/java/partypeople/server/util/ApiDocumentUtils.java
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: 기능, [BE]조국선, 리팩토링, 필수

#152 companion nation FK 관련 버그 수정
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
Labels: 버그, [BE]홍수경

#160 Feat/hsg/companion 동행글 단건조회 response 데이터 수정
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
Labels: [BE]홍수경

#176 Feat/jgs/member
  server/build.gradle
  server/src/main/java/partypeople/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/partypeople/server/auth/AuthService.java
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/partypeople/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/partypeople/server/auth/userdetails/MemberDetailService.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
  server/src/main/java/partypeople/server/init/initDb.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/dto/FollowDto.java
  server/src/main/java/partypeople/server/member/dto/MemberDto.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/mapper/MemberMapper.java
  server/src/main/java/partypeople/server/member/service/FollowService.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/response/ErrorResponse.java
  server/src/test/java/partypeople/server/config/SecurityConfigurationTest.java
  server/src/test/java/partypeople/server/controller/MemberControllerTest.java
  server/src/test/java/partypeople/server/member/controller/MemberControllerRestDocsTest.java
Labels: [BE]조국선

#185 :bug: fix : 탈퇴회원 로그인 시 처리 버그 수정
  server/src/main/java/partypeople/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/service/FollowService.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/review/repository/ReviewRepository.java
  server/src/main/java/partypeople/server/review/service/ReviewService.java
  server/src/test/java/partypeople/server/controller/MemberControllerTest.java
  server/src/test/java/partypeople/server/member/controller/MemberControllerRestDocsTest.java
Labels: [BE]조국선

#202 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
  server/src/test/java/partypeople/server/companion/controller/CompanionControllerTest.java
Labels: [BE]홍수경

#210 Feat/hsg/companion 테스트코드 작성
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/service/CompanionService.java
  server/src/test/java/partypeople/server/companion/controller/CompanionControllerTest.java
Labels: 문서, [BE]홍수경

#236 Feat/jgs/member
  server/.gitignore
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/partypeople/server/auth/AuthService.java
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/partypeople/server/auth/filter/JwtAuthorizationFilter.java
  server/src/main/java/partypeople/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/partypeople/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/partypeople/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/partypeople/server/auth/utils/ErrorResponder.java
  server/src/main/java/partypeople/server/companion/controller/CompanionController.java
  server/src/main/java/partypeople/server/config/BeanConfig.java
  server/src/main/java/partypeople/server/member/controller/MemberController.java
  server/src/main/java/partypeople/server/member/dto/FollowDto.java
  server/src/main/java/partypeople/server/member/dto/MemberDto.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/message/repository/MessageRepository.java
  server/src/main/java/partypeople/server/message/service/MessageService.java
  server/src/main/java/partypeople/server/review/service/ReviewService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/test/java/partypeople/server/InitDb.java
  server/src/test/java/partypeople/server/member/controller/MemberControllerRestDocsTest.java
  server/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  server/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: [BE]조국선

#243 :memo: docs : 문서 이름 수정
  server/src/test/java/partypeople/server/companion/controller/CompanionControllerTest.java
Labels: 문서, [BE]홍수경

#283 Feat/jgs/member
  server/src/main/java/partypeople/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/partypeople/server/exception/ExceptionCode.java
  server/src/main/java/partypeople/server/member/repository/MemberRepository.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/test/java/partypeople/server/member/service/MemberServiceTest.java
Labels: 기능, [BE]조국선

#287 Feat/hsg/companion
  server/src/main/java/partypeople/server/companion/dto/CompanionDto.java
  server/src/main/java/partypeople/server/companion/entity/Companion.java
  server/src/main/java/partypeople/server/companion/mapper/CompanionMapper.java
  server/src/test/java/partypeople/server/companion/controller/CompanionControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 문서, [BE]홍수경

#299 Feat/jgs/member
  server/src/main/java/partypeople/server/auth/configure/SecurityConfiguration.java
  server/src/main/java/partypeople/server/member/entity/Member.java
  server/src/main/java/partypeople/server/member/service/MemberService.java
  server/src/main/java/partypeople/server/message/service/MessageService.java
Labels: [BE]조국선

#318 Feat/hsg/companion
  server/src/test/java/partypeople/server/companion/controller/CompanionControllerTest.java
Labels: 문서, [BE]홍수경
